package com.taskvoice.util;

import com.taskvoice.model.Task;
import com.taskvoice.model.TimesheetEntry;
import com.taskvoice.model.User;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.util.List;

/**
 * PdfBuilder — builds a styled corporate work statement PDF.
 * Uses Apache PDFBox. Proper header/footer, TaskVoice branding.
 */
public class PdfBuilder {

    public static byte[] generateWorkStatement(User user, LocalDate from, LocalDate to,
                                                 List<TimesheetEntry> entries, List<Task> tasks) throws IOException {
        try (PDDocument doc = new PDDocument(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            PDPage page = new PDPage();
            doc.addPage(page);

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
                // Fonts
                PDType1Font fontBold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
                PDType1Font fontReg  = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

                float y = 750;

                // Header / Branding
                cs.beginText();
                cs.setFont(fontBold, 20);
                cs.newLineAtOffset(50, y);
                cs.showText("TASKVOICE — WORK STATEMENT");
                cs.endText();

                y -= 30;
                cs.beginText();
                cs.setFont(fontReg, 11);
                cs.newLineAtOffset(50, y);
                cs.showText("Employee: " + user.getName() + " (" + user.getEmployeeNo() + ")  |  Period: " + from + " to " + to);
                cs.endText();

                y -= 40;
                // Section 1: Summary Stats
                double totalHours = entries.stream().mapToDouble(TimesheetEntry::getDurationHours).sum();
                cs.beginText();
                cs.setFont(fontBold, 14);
                cs.newLineAtOffset(50, y);
                cs.showText("Summary Statistics");
                cs.endText();

                y -= 20;
                cs.beginText();
                cs.setFont(fontReg, 10);
                cs.newLineAtOffset(50, y);
                cs.showText("Total Logged Hours: " + String.format("%.2f", totalHours) + " hrs   |   Total Tasks: " + tasks.size());
                cs.endText();

                y -= 40;
                // Section 2: Tasks Overview
                cs.beginText();
                cs.setFont(fontBold, 14);
                cs.newLineAtOffset(50, y);
                cs.showText("Assigned Tasks & Performance");
                cs.endText();

                y -= 20;
                for (Task t : tasks) {
                    if (y < 80) break; // simple one-page safety boundary
                    cs.beginText();
                    cs.setFont(fontBold, 10);
                    cs.newLineAtOffset(50, y);
                    cs.showText("• " + t.getTitle() + " [" + t.getStatus() + "]");
                    cs.endText();

                    y -= 14;
                    cs.beginText();
                    cs.setFont(fontReg, 9);
                    cs.newLineAtOffset(65, y);
                    String gradeStr = t.getManagerGrade() != null ? "Grade: " + t.getGradeDisplay() + " | " : "";
                    cs.showText(gradeStr + "Expected: " + t.getExpectedHours() + "h | Actual: " + t.getActualHours() + "h");
                    cs.endText();
                    y -= 18;
                }

                // Footer
                cs.beginText();
                cs.setFont(fontReg, 8);
                cs.newLineAtOffset(50, 30);
                cs.showText("Generated by TaskVoice Enterprise System on " + LocalDate.now() + " — Official Document");
                cs.endText();
            }

            doc.save(out);
            return out.toByteArray();
        }
    }
}
